spring.application.name=onroot

# DB
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/OnRoot?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=seung0258
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

# Q-Net API
qnet.api.key=744b37ceb6156a26afbbe6639196427e483ff6f51f36885a4fa3802fb3d34af9
qnet.api.base-url=http://openapi.q-net.or.kr/api/service/rest/InquiryTestInformationNTQSVC

# 국가자격 시험일정 API (data.go.kr)
qualexam.api.key=744b37ceb6156a26afbbe6639196427e483ff6f51f36885a4fa3802fb3d34af9
qualexam.api.base-url=https://apis.data.go.kr/B490007/qualExamSchd
